variables:
  DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/fix/gitlabci"
  BASH_ENV: variables.sh
stages:
  - prepare
  - build
  - test


before_script:
    - echo "#!/bin/bash" > variables.sh
    - chmod +x variables.sh
    - mkdir -p build
    - curl -O "${DEPENDENCIES_BASE_URL}/environment.sh"
    - bash environment.sh
    - source variables.sh
    - rbenv install 2.3.3 -s

fetch_dependencies:
  stage: prepare
  script:
    - mkdir -p build
    - curl -O "${DEPENDENCIES_BASE_URL}/environment.sh"
    - chmod +x environment.sh
    - ./environment.sh
  tags:
    - xcode9.3

build_project:
  stage: build
  script:
    - chmod +x dependencies.sh
    - ./dependencies.sh
    - chmod +x build.sh
    - ./build.sh
  tags:
    - xcode9.3


test_project:
  stage: test
  script:
    - chmod +x test.sh
    - ./test.sh
    - chmod +x post_test.sh
    - ./post_test.sh
  tags:
    - xcode9.3

