defaults: &defaults
  environment:
    - DEPENDENCIES_BASE_URL: "https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master"
  macos:
    xcode: "9.4.1"
  shell: /bin/bash --login -eo pipefail

version: 2
jobs:
      
  build:
    <<: *defaults
    branches:
      ignore:
        - develop
    steps:
    - checkout
    - run: 
        name: "Setup gems"
        command: |
          curl -O "${DEPENDENCIES_BASE_URL}/Gemfile"
          curl -O "${DEPENDENCIES_BASE_URL}/Gemfile.lock"
          curl -O "${DEPENDENCIES_BASE_URL}/.ruby-version"
    - restore_cache: 
        keys: 
          - v1-carthage-{{ checksum "Cartfile.resolved" }}
          - v1-carthage-
    - restore_cache: 
        keys: 
          - v1-gems-{{ checksum "Gemfile.lock" }}
          - v1-gems-
    - run: 
        name: "Install gems"
        command: bundle install --path ~/.gem
    - save_cache: 
        key: - v1-gems-{{ checksum "Gemfile.lock" }}
        paths: ~/.gem
    - run: 
        name: "Build"
        command: bundle exec fastlane build
    - save_cache: 
        key: - v1-carthage-{{ checksum "Cartfile.resolved" }}
        paths: Carthage
    - run: 
        name: "Test"
        command: bundle exec fastlane test
    - run: 
        name: "Post test"
        command: bundle exec fastlane post_test
    - store_test_results:
        path: test

